## Script to extract input parameters

base = '/Users/NicoG/FS_in-house/outputs/'
setup = 'M1_1B_Nz_{0:02d}/'.format(ii)

fid = open([base setup 'codes_etc/input/problem_params'])
#fid = fopen([base 'codes_etc/input/problem_params'])
pr_par  = textscan(fid,'#s #*[^\n]')

nx       = pr_par{1}(2)  
nx      = str2num(nx{1})
ny       = pr_par{1}(3)  
ny      = str2num(ny{1})
nz       = pr_par{1}(4)  
nz      = str2num(nz{1})
nL       = pr_par{1}(5)  
nL      = str2num(nL{1})
nsp      = pr_par{1}(6)  
nsp     = str2num(nsp{1})
dt       = pr_par{1}(7)  
dt      = str2num(dt{1})
t_start  = pr_par{1}(8)  
t_start = str2num(t_start{1})
t_end    = pr_par{1}(9)  
t_end   = str2num(t_end{1})
BCs      = pr_par{1}(10) 
BCs     = BCs{1}
Lx       = pr_par{1}(11) 
Lx      = str2num(Lx{1})
Ly       = pr_par{1}(12) 
Ly      = str2num(Ly{1})
Lz       = pr_par{1}(13) 
Lz      = str2num(Lz{1})
g        = pr_par{1}(17) 
g       = str2num(g{1})
f        = pr_par{1}(18) 
f       = str2num(f{1})
rho_0    = pr_par{1}(19) 
rho_0   = str2num(rho_0{1})
nuh      = pr_par{1}(20) 
nuh     = str2num(nuh{1})
nuz      = pr_par{1}(21) 
nuz     = str2num(nuz{1})
kappah   = pr_par{1}(22) 
kappah  = str2num(kappah{1})
kappaz   = pr_par{1}(23) 
kappaz  = str2num(kappaz{1})
kappahPT = pr_par{1}(24) 
kappahPT= str2num(kappahPT{1})
kappazPT = pr_par{1}(25) 
kappazPT= str2num(kappazPT{1})
hdeg     = pr_par{1}(26) 
hdeg    = str2num(hdeg{1})
dgrad    = pr_par{1}(27) 
dgrad   = str2num(dgrad{1})
#if strcmp(setup(3),'p')
#    if str2num(setup(8:9)) >= 18
nuh2     = pr_par{1}(31) 
nuh2     = str2num(nuh2{1})
nuz2     = pr_par{1}(32) 
nuz2     = str2num(nuz2{1})
kappah2  = pr_par{1}(33) 
kappah2  = str2num(kappah2{1})
kappaz2  = pr_par{1}(34) 
kappaz2  = str2num(kappaz2{1})
kappahPT2= pr_par{1}(35) 
kappahPT2= str2num(kappahPT2{1})
kappazPT2= pr_par{1}(36) 
kappazPT2= str2num(kappazPT2{1})
hdeg2    = pr_par{1}(37) 
hdeg2    = str2num(hdeg2{1})
nlflag   = pr_par{1}(38) 
nlflag   = str2num(nlflag{1})

fclose(fid)